version: '3.1'

services:
  mysql:
    image: mysql:8.0.33
    container_name: 'java-mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - 3307:3306

  rest_js:
    build: ./
    ports:
      - "8081:8080"
    restart: on-failure
    environment:
      spring.datasource.url:
        "jdbc:mysql://mysql:3306/db?verifyServerCertificate=false&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC"